# Generated by Django 4.2.1 on 2023-05-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_service_provider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='service',
            field=models.CharField(blank=True, choices=[('Photographer', 'Photographer'), ('Makup_artist', 'Makup-artist'), ('Hall_owner', 'Hall owner'), ('Hotel_owner', 'Hotel owner'), ('Car_gallary_owner', 'Car gallary owner'), ('Shop_owner', 'Shop owner'), ('Sound_System', 'Sound System')], max_length=30, null=True),
        ),
    ]
